### ISSUE TITLE
Timing and creating entities

### ISSUE THREAD

**Issue by empyreanx** [abeimler/ecs_benchmark#11]
For the 3 systems with mixed entities benchmark, is the time to create and add entities to the systems included in the total time? I've written my own simple ECS and I'm trying to recreate the benchmarks and apply them as accurately as I can.

**Comment by abeimler** [comment]
Hi,
if you look at the benchmark [BM_SystemsUpdateMixedEntities](https://github.com/abeimler/ecs_benchmark/blob/master/benchmark/benchmarks/ECSBenchmark.h#L70) (and know a bit about [google-benchmark](https://github.com/google/benchmark)), the entities get created first and then the `app.update(fakeTimeDelta);` get measured.

_(if you are looking for the specific google-benckmark, you can find them in the [plot.config.json](https://github.com/abeimler/ecs_benchmark/blob/master/plot.config.json), just look up at the regex (matching name of the google-benchmark) and the matching title)_

_You can also have a look at [https://github.com/skypjack/entt/blob/master/test/benchmark/benchmark.cpp](entt benchmark) or [OpenEcs benchmark](https://github.com/Gronis/OpenEcs/blob/master/test/ecs_performance.cpp)_

**Comment by abeimler** [comment]
I'm adding [pico_header/pico_ecs](https://github.com/abeimler/ecs_benchmark/tree/feature/pico_ecs)
