### ISSUE TITLE
pico_ecs: NDEBUG

### ISSUE THREAD

**Issue by empyreanx** [abeimler/ecs_benchmark#12]
pico_ecs should be compiled with the NDEBUG flag to turn off debug mode. Otherwise pico_ecs will perform a lot of checks that are not present in release mode, and thus will not accurately represent the runtime efficiency of the library.

**Comment by abeimler** [comment]
This shouldn't be a problem, I'm using CMake 3.27.1 and built in Release Mode ... CMake adds `NDEBUG` on its own.

```cmake
//Flags used by the CXX compiler during RELEASE builds.
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
```

You can always add the flag by yourself...
```cmake
target_compile_definitions(pico_ecs INTERFACE $<$<CONFIG:Release>:NDEBUG>)
```

**Comment by empyreanx** [comment]
Thanks for clearing that up.
