### ISSUE TITLE
Failing to build on Windows due to missing Artemis github?

### ISSUE THREAD

**Issue by Cirtoyt** [abeimler/ecs_benchmark#7]
Hi, I've been attempting to build the solution and have run into an error where the artemis git repo seems to not be publically available causing the ./configure command to fail.

I've attempted to comment out the artemis repo fetch within the main CMakeLists.txt file, to comment out the benchmark calls in the CMakeLists.txt files within src and app folders, and remove references to artemis from the run_benchmark files, but the ./configure.sh fails.

The current error:
`Make Error at cmake/ClangFormat.cmake:17 (message):
  ClangFormat: clang-format not found! Aborting
Call Stack (most recent call first):
  CMakeLists.txt:188 (clangformat_setup)`

What do you suppose I should do?
Maybe you could remove Artemis form the project for me?

**Comment by abeimler** [comment]
Seem like clang-format is required.

Check out the new release, I rewrite everything, so this should work now.

**Comment by abeimler** [comment]
Building for windows almost works for me.

The [mustache](https://github.com/kirillochnev/mustache) framework has some problems, waiting for https://github.com/kirillochnev/mustache/issues/53

**Comment by abeimler** [comment]
This should work for windows now https://github.com/abeimler/ecs_benchmark/actions/workflows/windows.yml
