### ISSUE TITLE
Add benchmark of new ECS framework

### ISSUE THREAD

**Issue by kirillochnev** [abeimler/ecs_benchmark#8]
Hello, if I create a benchmark for my C++ ECS (https://github.com/kirillochnev/mustache), can I publish it here?

**Comment by abeimler** [comment]
Hi,
I add your framework to the new version (4.0.0).

I also check out your [ecs-benchmark](https://github.com/kirillochnev/ecs-benchmark)/[mustache performance](https://github.com/kirillochnev/mustache#performance=) and add OpenEcs and a little OOP solution.
