### ISSUE TITLE
Mustache benchmark update

### ISSUE THREAD

**Issue by kirillochnev** [abeimler/ecs_benchmark#9]
Hi, there is 2 ways you can improve performance of tests: "Get n components from Entity".
1) If you don't need mutable component, you can require "const T" instead of "T". Mustache has built in version control system, so each time you get mutable component mustache updates component version. 
2) If you 100% sure that entity is valid and has component you can get it this way world.entities().getComponent<const T, mustache::FunctionSafety::kUnsafe>(entity);`

**Comment by abeimler** [comment]
I think [this](https://github.com/abeimler/ecs_benchmark/pull/10/files#diff-e848bc3654bed75f2803e04dc912e8cb4838be9569cc6380095ad972f04801a7=) is what you want.

https://github.com/abeimler/ecs_benchmark/pull/10

**Comment by abeimler** [comment]
@kirillochnev 
I think the PR (#10) is ready, if you want you can give further suggestions and approve it ^^
